# Warm-start training (Focal Loss)
# scripts/run_5fold_pipeline.py
# ===================================================================
# PRISM-DDI: 5-Fold Cross Validation Pipeline
# 
# Process:
# 1. Combines tr/val/tst csvs into one pool.
# 2. Splits into 5 Folds.
# 3. For each fold:
#    - Split Train(90%)/Valid(10%).
#    - Augment Train (5x).
#    - Generate TFRecords.
#    - Train Model.
#    - Evaluate on Test Fold.
# ===================================================================
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
import shutil

# --- Setup ---
# Hardcoded paths to your ORIGINAL source files (verify these exist!)
RAW_DIR = "data/raw"
SOURCE_FILES = ["tr_dataset.csv", "val_dataset.csv", "tst_dataset.csv"] 

# Command prefix
CMD_PREFIX = "LD_LIBRARY_PATH=/root/anaconda3/envs/prism_gpu/lib python"

def run_cmd(cmd):
    print(f"\n🚀 Running: {cmd}")
    ret = os.system(cmd)
    if ret != 0: 
        raise RuntimeError(f"Command failed: {cmd}")

def main():
    print("=== STARTING PRISM-DDI 5-FOLD CV ===")
    
    # 1. Load and Merge Data
    print("Loading source data...")
    dfs = []
    for f in SOURCE_FILES:
        path = os.path.join(RAW_DIR, f)
        if os.path.exists(path):
            dfs.append(pd.read_csv(path))
        else:
            print(f"Warning: Source file {f} not found, skipping.")
    
    if not dfs: raise ValueError("No data found!")
    
    full_df = pd.concat(dfs).reset_index(drop=True)
    # Shuffle consistently
    full_df = full_df.sample(frac=1, random_state=42).reset_index(drop=True)
    print(f"Total Samples: {len(full_df)}")
    
    # 2. K-Fold Loop
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    final_scores = []
    
    # Create a results log file
    with open("results/5fold_summary.txt", "w") as f:
        f.write("Fold,Accuracy,AUROC,AUPR,F1\n")

    for fold_idx, (train_full_idx, test_idx) in enumerate(kf.split(full_df)):
        fold_num = fold_idx + 1
        print(f"\n\n{'='*40}")
        print(f"🔄 PROCESSING FOLD {fold_num} / 5")
        print(f"{'='*40}")
        
        # A. Split Data
        df_test = full_df.iloc[test_idx]
        df_train_all = full_df.iloc[train_full_idx]
        
        # Further split Train into Train(90%) / Valid(10%) for Early Stopping
        # We must do this to avoid using Test set for stopping
        split_n = int(len(df_train_all) * 0.9)
        df_train = df_train_all.iloc[:split_n]
        df_valid = df_train_all.iloc[split_n:]
        
        print(f"Split sizes -> Train: {len(df_train)}, Valid: {len(df_valid)}, Test: {len(df_test)}")
        
        # B. Save Temp Files (for scripts to read)
        # Note: augment_data.py reads 'temp_fold_train_raw.csv'
        df_train.to_csv(os.path.join(RAW_DIR, "temp_fold_train_raw.csv"), index=False)
        # Config points VALID/TEST to these:
        df_valid.to_csv(os.path.join(RAW_DIR, "temp_fold_val.csv"), index=False)
        df_test.to_csv(os.path.join(RAW_DIR, "temp_fold_test.csv"), index=False)
        
        # C. Augment Data
        # Generates 'temp_fold_train_aug.csv' and 'temp_fold_features.npy'
        run_cmd(f"{CMD_PREFIX} scripts/augment_data.py")
        
        # D. Generate TFRecords
        # Reads the temp csvs and npy from config, writes to 'data/processed/tfrecords/'
        # First, clean old records to be safe
        os.system(f"rm -rf data/processed/tfrecords/*")
        run_cmd(f"{CMD_PREFIX} scripts/create_tfrecords.py")
        
        # E. Train
        # Trains and saves '_best.h5'
        run_cmd(f"{CMD_PREFIX} scripts/train.py")
        
        # F. Evaluate
        # We use evaluate_final.py to get scores on the current temp_fold_test.csv
        print("Evaluating Fold...")
        # Capture output is tricky with os.system, so we rely on evaluate_final writing to a file
        # or we just let it print to stdout and trust the process.
        # Ideally, evaluate_final.py should append to a log.
        # Let's run it.
        run_cmd(f"{CMD_PREFIX} scripts/evaluate_final.py > results/fold_{fold_num}_log.txt")
        
        # Parse result from log (Simple parser)
        acc = 0.0
        try:
            with open(f"results/fold_{fold_num}_log.txt", "r") as f:
                content = f.read()
                print(content) # Show in main log
                for line in content.split('\n'):
                    if "Accuracy :" in line:
                        acc = float(line.split(":")[1].strip())
        except:
            print("Error parsing result.")
            
        final_scores.append(acc)
        
        # G. Archive Model
        # Rename the best model so it isn't overwritten by next fold
        import glob
        # Find the best model file generated by train.py
        model_files = glob.glob(os.path.join("results/trained_models", "*_best.h5"))
        if model_files:
            # Sort by modified time
            latest_model = max(model_files, key=os.path.getmtime)
            archive_name = os.path.join("results/trained_models", f"PRISM_5Fold_Fold{fold_num}.h5")
            shutil.move(latest_model, archive_name)
            print(f"Model archived to: {archive_name}")
            
        # Log score
        with open("results/5fold_summary.txt", "a") as f:
            f.write(f"{fold_num},{acc},,,\n")

    print("\n\n=== CROSS VALIDATION COMPLETE ===")
    print(f"Scores: {final_scores}")
    print(f"Mean Accuracy: {np.mean(final_scores):.4f} +/- {np.std(final_scores):.4f}")

if __name__ == "__main__":
    main()
